odin_facebook/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }
	
	root 'static_pages#home'

	devise_scope :user do
	  get '/sign_in', to: 'devise/sessions#new'
	  get '/sign_out', to: 'devise/sessions#destroy'
	  get '/sign_up', to: 'devise/registrations#new'
	end
	resources :users, 	 only: 	 [:show, :index] do
		member do
			get :friends, :notifications
		end
	end
	
	resources :posts, 	 except: [:index] do 
		resources :comments, only: 	 [:new, :create, :destroy]
		resources :likes, 	 only: 	 [:create, :destroy, :index]
	end
  resources :friendships,        only: [:create, :destroy, :update]

end

odin_facebook/app/views/shared/_comment_form.html.erb
<%= form_for @comment, url: post_comments_path(@comment.post), html: { multipart: true } do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.text_area :content, placeholder: "Write a comment...", cols: 60,rows: 3 %> <br /> 
	<%= f.label "picture-upload", "&#x1f4f7; add a picture".html_safe, class: "file-upload" %>
	<%= f.file_field :comment_picture, accept: 'image/png,image/gif,image/jpeg', id: "comment_picture-upload" %><br />
	<%= f.submit "comment", class: "submit" %>
<% end %>

odin_facebook/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

odin_facebook/app/views/shared/_like_form.html.erb
<% if current_user.already_likes?(@post) %>
	<%= render './posts/unlike_button' %>
<% else %>
	<%= render './posts/like_button' %>
<% end %> 

odin_facebook/app/views/shared/_notifications.html.erb
<% if current_user.pending_requests.any? %> 
	<%= link_to pluralize(current_user.pending_requests.count, ""), notifications_user_path(current_user) %>
<% end %>

odin_facebook/app/views/shared/_post_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<h3>
		<%= gravatar_for @post.user %>
		Write a new post
	</h3>
	<%= f.text_area :content, placeholder: "What's on your mind?", cols: 44, rows: 5 %> <br />
	<%= f.label "picture-upload", "&#x1f4f7; add a picture".html_safe, class: "file-upload", id: "file" %>
	<%= f.file_field :picture, accept: 'image/png,image/gif,image/jpeg', id: "post_picture-upload" %>
	<hr>
	<%= f.submit "Post", class: "submit" %>
<% end %>